config/routes.rb
ElUser::Application.routes.draw do
  resources :sessions, :only => %w{create}
  get 'signin' => 'sessions#new', :as => :signin
  get 'signout' => 'sessions#destroy', :as => :signout
  get 'logout' => 'sessions#show',  :as => :logout

  get 'signup' => 'profiles#new', :as => :signup
  get 'profile' => 'profiles#edit', :as => :profile

  get 'password' => 'passwords#edit', :as => :password
  put 'password' => 'passwords#update', :as => :password
  resources :passwords do
    collection do
      get :forgot
      post :reset
    end
  end

  resources :session_services, :only => %w{create}

  resources :profile_services, :only => %w{create update}

  resources :password_services, :only => %w{update}
  
  resources :user_services, :only => %w{create}
  
  resources :right_services do
    collection do 
      post :reset_rights
    end
  end 
  
  resources :profiles do
    member do
      post :update_role
    end
  end
  
  resources :partner_sessions do
    collection do
      get :authenticate
      get :login
    end
  end
  
  namespace :setting do
    resources :rights
    resources :roles do
      resources :link_groups, :link_group_links
    end
  end
  
  

  root :to => "profiles#index"

end

app/models/right.rb
class Right < ActiveRecord::Base
  belongs_to :parent, :class_name => "Right"
  has_many :children, :class_name => "Right", :foreign_key => "parent_id", :dependent => :destroy, :order => "name"
  has_many :role_rights, :dependent => :destroy
  def roles; self.role_rights.all(:include => :role, :order=>"role_id").map(&:role); end
  named_scope :roots, :conditions=>"parent_id is null", :include => :children
  named_scope :recent_updated, lambda{{:conditions => ["updated_at >= ?", 5.days.ago]}}
  named_scope :eleutian_rights, :conditions => "parent_id is null and right_type = 'eleutian'"

  after_create :update_root
  def update_root
    unless self.parent.blank?
      self.root.update_attribute(:updated_at, Time.now)
    end
  end

  def self.reset(data)
    dt = DataTree.build(data)
    app = self.find(:first, :conditions=>["name=? and parent_id is null", dt.root.data])
    app.blank? ? Right.new.create_children_from_node(dt.root) : recur_reset(app, dt.root)
  end
  
  def self.reset_rails3(app_name, controllers)
        
    app = self.find_or_create_by_name_and_right_type(app_name, 'eleutian')
    controllers ||= []
    children = app.children.map(&:name)
    
    added = controllers - children
    removed = children - controllers
    added.each do |controller|
      app.children.create(:name => controller, :right_type => 'eleutian')
    end
    removed.each do |controller|
      app.children.find_by_name(controller).try(:destroy)
    end
  end

  def create_children_from_node(node)
    right = Right.create(:name => node.data, :parent_id => self.id)
    node.children.each{|child| right.create_children_from_node(child)}
  end

  def full_path
    ([(parent.blank? ? nil : parent.full_path), name]-[nil]).join("/")
  end

  def url(domain)
    parent.blank? ? "http://#{name}.#{domain.name}.com" : [parent.url(domain), name].join("/")
  end

  def root
    self.parent.blank? ? self : parent.root
  end

  def depth
    self.parent.blank? ? 0 : self.parent.depth + 1
  end

  def auto_set?
    true
  end

  def reset_roles(role_ids, in_recusive = false)
    return if role_ids.blank?
    if self.children.blank?
      self.role_rights.delete_all unless in_recusive
      self.add_roles(role_ids)
    else
      self.children.each{|child| child.reset_roles(role_ids, true)}
    end
  end

  def add_roles(role_ids)
    role_ids.each do |role_id|
      self.role_rights.create(:role_id => role_id) if self.role_rights.find_by_role_id(role_id).blank?
    end
  end

  private
  def self.recur_reset(right, node)
    deleted = []
    right.children.each{|child|
      n = node.children.select{|t| t.data == child.name}.first
      if n.blank? 
        deleted << child if child.auto_set?
      else
        recur_reset(child, node.children.delete(n))
      end
    }
    deleted.each{|r| r.destroy}
    node.children.each{|n| right.create_children_from_node(n)}
  end
end

app/controllers/setting/base_controller.rb
class Setting::BaseController < ApplicationController
  # before_filter :root_required
  # before_filter :find_role
  # cache_sweeper :setting_sweeper

  # protected
  # def find_role
  #   @role = Role.find_by_id(params[:role_id]||params[:id])
  # end
end

app/controllers/setting/link_groups_controller.rb
class Setting::LinkGroupsController < Setting::BaseController
  in_place_edit_for :link, :name_en, :name_zh, :app, :path, :target_page, :description_en, :description_zh
  in_place_edit_for :link_group, :name_en, :name_zh
  in_place_edit_for :link_group_link, :position

  def index
    if params[:role_id]
      @role = Role.find params[:role_id]
    end
  end
  
  def new
    render :layout => false
  end
    # 
    # def set_link_group_name_en
    # end

  def create
    @link_group = @role.link_groups.new(params[:link_group])
    if @link_group.save
      redirect_to setting_role_link_groups_path(@role)
    else
      render :action => :new, :layout => true
    end
  end

  def destroy
    LinkGroup.find_by_id(params[:id]).try(:destroy)
    redirect_to setting_role_link_groups_path(@role)
  end
end

app/controllers/setting/rights_controller.rb
class Setting::RightsController < Setting::BaseController
  before_filter :find_right, :only => [:edit, :update, :destroy, :show]

  def new
    render :layout => false
  end

  def create
    ManuallyAddedRight.create(:name => params[:name], :parent_id => params[:parent_id])
    redirect_to setting_right_path(params[:parent_id])
  end
  
  def index
    @role = Role.find_by_id(params[:role_id]||params[:id])
    
    @right_lists = Right.eleutian_rights
    if params[:right_id]
      @right = Right.find params[:right_id]
    else
      @right = @right_lists.first || 0      
    end
    
  end
  
  def edit
    render :layout => false
  end

  def update
    @right.reset_roles(params[:role].keys)
    redirect_to :action => :index, :right_id => @right.root.id
  end

  def destroy
    @right.try(:destroy)
    render :nothing => true
  end

  def list
    render :layout => false
  end

  private
  def find_right
    @right = Right.find_by_id(params[:id])
  end
end

app/controllers/setting/roles_controller.rb
class Setting::RolesController < Setting::BaseController
  def show
    @role = Role.find_by_id(params[:id])
    # @profile_roles = ProfileRole.of_role(@role).combo_search(params, :include => :profile)
  end

  def destroy
    ProfileRole.find_by_id(params[:id]).try(:destroy)
    render :nothing => true
  end
end

app/views/setting/rights/_right.html.erb
<tr id="<%= right.dom_id %>"<%= " class='parent-right'" if right.children.present? %>>
  <td><%= popup t(:edit), edit_setting_right_path(right) %></td>
  <% if right.children.size == 0 %>
    <td style="padding-left:<%= right.depth * 50 %>px;">
      <%= right.name %>
    </td>
    <td><%= right.roles.map{|t| t.try(:name)}.join(' ') %></td>
  <% else %>
    <td style="padding-left:<%= right.depth * 50 %>px;" colspan="2" ><%= right.name %></td>
  <% end %>
</tr>
<%= render right.children %>

app/views/setting/rights/_role.html.erb
<li>
  <% checked = @right.roles.include?(role)  %>
<%= check_box_tag "role[#{role.id}]", role.id, checked, :id=>role.dom_id %><label for="<%= role.dom_id %>"<%= " style='color:red'" if checked %>><%= role.name %></label>
  <% if role.children.present? %>
    <ul>
      <%= render :partial => "role", :collection => role.children %>
    </ul>
  <% end %>
</li>

app/views/setting/rights/edit.html.erb
<% form_tag setting_right_path(@right), :method => :put do %>
  <ul class="role_list">
    <%= render :partial => "role", :collection => Role.roots %>
  </ul>
  <%= submit_tag t(:submit) %>
<% end %>
<%#= role_right_tag(@role, @right) %>

app/views/setting/rights/index.html.erb
<div style="clear:both;">
	<div style="width:18%;;float:left;">
		<ul style="border:1px #577BBF solid;padding:10px;margin:0px 20px;">
			<% @right_lists.each_with_index do |item, index| %>
				<% if index % 2 == 0 %>
					<li style="list-style:none;background:#E6EDFF;"><%=link_to item.name, setting_rights_path(:right_id => item.id)%></li>
				<% else %>
					<li style="list-style:none;background;"><%=link_to item.name, setting_rights_path(:right_id => item.id)%></li>
				<% end %>
			<% end %>
		</ul>
	</div>
	<div>
		<table style="width:80%;" class="list_table" >
			<thead>
				<th><%= t :edit %></th>
				<th><%= t :right %></th>
				<th><%= t :role %></th>
			</thead>
			<tbody>
			    <%= render :partial => "right", :collection => @right.children %>
			</tbody>
		</table>
	</div>
</div>
<script>
$(document).ready(function(){
	li = $(".hmenu2").find("li").removeClass('active')[1];
	$(li).addClass("active");
})
</script>