config/routes.rb
ElUser::Application.routes.draw do
  resources :sessions, :only => %w{create}
  get 'signin' => 'sessions#new', :as => :signin
  get 'signout' => 'sessions#destroy', :as => :signout
  get 'logout' => 'sessions#show',  :as => :logout

  get 'signup' => 'profiles#new', :as => :signup
  get 'profile' => 'profiles#edit', :as => :profile

  get 'password' => 'passwords#edit', :as => :password
  put 'password' => 'passwords#update', :as => :password
  resources :passwords do
    collection do
      get :forgot
      post :reset
    end
  end

  resources :session_services, :only => %w{create}

  resources :profile_services, :only => %w{create update}

  resources :password_services, :only => %w{update}
  
  resources :user_services, :only => %w{create}
  
  resources :right_services do
    collection do 
      post :reset_rights
    end
  end 
  
  resources :profiles do
    member do
      post :update_role
    end
  end
  
  resources :partner_sessions do
    collection do
      get :authenticate
      get :login
    end
  end
  
  namespace :setting do
    resources :rights
    resources :roles do
      resources :link_groups, :link_group_links
    end
  end
  
  

  root :to => "profiles#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElUser</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
<div style="float:right;padding:0 20px;">
    <% if current_user %>
      <%= current_user.login %>
      <%= link_to 'logout', signout_path, :method => :delete %>
</div>   
	<div style="clear:both;"></div>

	<div class="hmenu2">
		<ul>
	      <li class="active"> <%= link_to 'User Roles', profiles_path %></a></li>
	      <li><%= link_to 'Role Rights', setting_rights_path %></li>
	      <li><%=link_to 'Role Settings', setting_role_link_groups_path(515)%></a></li>
	    </ul>
 
<% else %>
      <%= link_to 'login', signin_path %>
    <% end %>
</div>

 <%= yield %>

  </body>
</html>